from __future__ import annotations

from dataclasses import replace
from pathlib import Path

from dba_assistant.application.request_models import (
    DEFAULT_MYSQL_DATABASE,
    DEFAULT_MYSQL_STAGE_BATCH_SIZE,
)
from dba_assistant.core.reporter.output_path_policy import ensure_report_output_path
from dba_assistant.core.reporter.types import OutputMode, ReportFormat, ReportOutputConfig


def render_analysis_output(
    analysis,
    *,
    runtime_inputs,
    output_mode: str,
    report_format: str,
    output_path: Path | None,
    template_name: str = "rdb-analysis",
    prompt: str = "",
) -> str:
    from dba_assistant.core.reporter.generate_analysis_report import (
        generate_analysis_report as _generate,
    )

    # Hard guard: force DOCX when the original prompt demands it.
    if prompt and _prompt_requests_docx_output(prompt) and report_format != "docx":
        output_mode = "report"
        report_format = "docx"

    effective_runtime_inputs = ensure_report_output_path(
        replace(
            runtime_inputs,
            output_mode=output_mode,
            report_format=report_format,
            output_path=output_path,
        ),
        report_format,
        report_slug=template_name,
    )
    fmt = ReportFormat.SUMMARY if report_format == "summary" else ReportFormat.DOCX
    if fmt is ReportFormat.DOCX and effective_runtime_inputs.output_path is None:
        return "Error: DOCX output requires an output path."

    config = ReportOutputConfig(
        mode=OutputMode.SUMMARY if output_mode == "summary" else OutputMode.REPORT,
        format=fmt,
        output_path=effective_runtime_inputs.output_path,
        template_name=template_name,
        language=getattr(analysis, "language", "zh-CN"),
    )
    artifact = _generate(analysis, config)

    # Postcondition: when DOCX was requested, verify the artifact path exists.
    if fmt is ReportFormat.DOCX:
        if artifact.output_path is not None and artifact.output_path.exists():
            return str(artifact.output_path)
        if artifact.output_path is not None:
            return f"Error: DOCX generation completed but artifact not found at {artifact.output_path}"
        return "Error: DOCX output was requested but no artifact path was generated by the reporter."

    if artifact.content is not None:
        return artifact.content
    if artifact.output_path is not None:
        return str(artifact.output_path)
    return "Analysis complete but no output generated."


def _prompt_requests_docx_output(prompt: str) -> bool:
    """Detect if the user prompt explicitly requests DOCX/Word output."""
    _docx_tokens = {"word", "docx", "doc", "文档", "报告"}
    lower = prompt.lower()
    return any(token in lower for token in _docx_tokens)


def append_mysql_runtime_note(content: str, *, analysis) -> str:
    metadata = getattr(analysis, "metadata", None)
    if not isinstance(metadata, dict):
        return content
    if metadata.get("route") != "database_backed_analysis":
        return content
    database_name = str(metadata.get("mysql_database") or "").strip() or DEFAULT_MYSQL_DATABASE
    table_name = str(metadata.get("mysql_table") or "").strip() or "unknown"
    staged_rows = str(metadata.get("mysql_staged_rows") or "0")
    batch_size = str(metadata.get("mysql_stage_batch_size") or DEFAULT_MYSQL_STAGE_BATCH_SIZE)
    cleanup_mode = str(metadata.get("mysql_cleanup_mode") or "retain")
    progress = str(metadata.get("mysql_progress") or "").strip()
    lines = [
        "[MySQL-backed staging]",
        f"database={database_name}",
        f"table={table_name}",
        f"staged_rows={staged_rows}",
        f"batch_size={batch_size}",
        "shared_table_mode=yes",
        "full_table_reload=disabled",
        f"cleanup_mode={cleanup_mode}",
    ]
    if progress:
        lines.append(f"progress={progress}")
    note = "\n".join(lines)
    if note in content:
        return content
    return f"{content}\n\n{note}"
