DEFAULT_DOCX_TABLE_STYLE = "Table Grid"

DOCX_TABLE_HEADER_FILL = "D9E2F3"
DOCX_TABLE_BORDER_COLOR = "A6A6A6"
DOCX_TABLE_TOTAL_WIDTH_INCHES = 6.2
DOCX_TABLE_MIN_COL_WIDTH_INCHES = 1.0
DOCX_TABLE_MAX_COL_WIDTH_INCHES = 3.0
